services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "wjMZTZe6f6j45GA"
      MYSQL_ROOT_PASSWORD: "Yp8rLuqQ7MEM8Y"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - ./mysql:/var/lib/mysql
volumes:
  mysql:
    driver: local